In [1]:
#Importing the necessary Libraries
import requests
import bs4
from bs4 import BeautifulSoup
import re
import pandas as pd
import numpy as np

In [2]:
##Lists for storing the extracted values
venue,city=[],[] #Venue and City details
tow,tod=[],[] #toss winner and toss decision details
match_date,match_num=[],[] #Match date and Match Number
over,ball,score=[],[],[] #Overnumber,ballnumber, and Score details
batting_team,bowling_team,innings=[],[],[]
batter,bowling=[],[]
team1_list,team2_list=[],[]

In [3]:
urls=['https://www.espncricinfo.com/series/ipl-2025-1449924/kolkata-knight-riders-vs-royal-challengers-bengaluru-1st-match-1473438/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/sunrisers-hyderabad-vs-rajasthan-royals-2nd-match-1473439/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/chennai-super-kings-vs-mumbai-indians-3rd-match-1473440/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/delhi-capitals-vs-lucknow-super-giants-4th-match-1473441/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/gujarat-titans-vs-punjab-kings-5th-match-1473442/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/rajasthan-royals-vs-kolkata-knight-riders-6th-match-1473443/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/sunrisers-hyderabad-vs-lucknow-super-giants-7th-match-1473444/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/chennai-super-kings-vs-royal-challengers-bengaluru-8th-match-1473445/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/gujarat-titans-vs-mumbai-indians-9th-match-1473446/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/delhi-capitals-vs-sunrisers-hyderabad-10th-match-1473447/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/rajasthan-royals-vs-chennai-super-kings-11th-match-1473448/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/mumbai-indians-vs-kolkata-knight-riders-12th-match-1473449/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/lucknow-super-giants-vs-punjab-kings-13th-match-1473450/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/royal-challengers-bengaluru-vs-gujarat-titans-14th-match-1473451/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/kolkata-knight-riders-vs-sunrisers-hyderabad-15th-match-1473452/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/lucknow-super-giants-vs-mumbai-indians-16th-match-1473453/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/chennai-super-kings-vs-delhi-capitals-17th-match-1473454/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/punjab-kings-vs-rajasthan-royals-18th-match-1473455/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/sunrisers-hyderabad-vs-gujarat-titans-19th-match-1473457/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/mumbai-indians-vs-royal-challengers-bengaluru-20th-match-1473458/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/kolkata-knight-riders-vs-lucknow-super-giants-21st-match-1473456/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/punjab-kings-vs-chennai-super-kings-22nd-match-1473459/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/gujarat-titans-vs-rajasthan-royals-23rd-match-1473460/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/royal-challengers-bengaluru-vs-delhi-capitals-24th-match-1473461/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/chennai-super-kings-vs-kolkata-knight-riders-25th-match-1473462/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/lucknow-super-giants-vs-gujarat-titans-26th-match-1473463/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/sunrisers-hyderabad-vs-punjab-kings-27th-match-1473464/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/rajasthan-royals-vs-royal-challengers-bengaluru-28th-match-1473465/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/delhi-capitals-vs-mumbai-indians-29th-match-1473466/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/lucknow-super-giants-vs-chennai-super-kings-30th-match-1473467/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/punjab-kings-vs-kolkata-knight-riders-31st-match-1473468/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/delhi-capitals-vs-rajasthan-royals-32nd-match-1473469/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/mumbai-indians-vs-sunrisers-hyderabad-33rd-match-1473470/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/royal-challengers-bengaluru-vs-punjab-kings-34th-match-1473471/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/gujarat-titans-vs-delhi-capitals-35th-match-1473472/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/rajasthan-royals-vs-lucknow-super-giants-36th-match-1473473/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/punjab-kings-vs-royal-challengers-bengaluru-37th-match-1473474/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/mumbai-indians-vs-chennai-super-kings-38th-match-1473475/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/kolkata-knight-riders-vs-gujarat-titans-39th-match-1473476/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/lucknow-super-giants-vs-delhi-capitals-40th-match-1473477/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/sunrisers-hyderabad-vs-mumbai-indians-41st-match-1473478/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/royal-challengers-bengaluru-vs-rajasthan-royals-42nd-match-1473479/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/chennai-super-kings-vs-sunrisers-hyderabad-43rd-match-1473480/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/mumbai-indians-vs-lucknow-super-giants-45th-match-1473482/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/delhi-capitals-vs-royal-challengers-bengaluru-46th-match-1473483/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/rajasthan-royals-vs-gujarat-titans-47th-match-1473484/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/delhi-capitals-vs-kolkata-knight-riders-48th-match-1473485/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/chennai-super-kings-vs-punjab-kings-49th-match-1473486/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/rajasthan-royals-vs-mumbai-indians-50th-match-1473487/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/gujarat-titans-vs-sunrisers-hyderabad-51st-match-1473488/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/royal-challengers-bengaluru-vs-chennai-super-kings-52nd-match-1473489/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/kolkata-knight-riders-vs-rajasthan-royals-53rd-match-1473490/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/punjab-kings-vs-lucknow-super-giants-54th-match-1473491/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/mumbai-indians-vs-gujarat-titans-56th-match-1473493/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/kolkata-knight-riders-vs-chennai-super-kings-57th-match-1473494/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/rajasthan-royals-vs-punjab-kings-59th-match-1473497/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/delhi-capitals-vs-gujarat-titans-60th-match-1473498/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/lucknow-super-giants-vs-sunrisers-hyderabad-61st-match-1473499/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/chennai-super-kings-vs-rajasthan-royals-62nd-match-1473500/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/mumbai-indians-vs-delhi-capitals-63rd-match-1473501/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/gujarat-titans-vs-lucknow-super-giants-64th-match-1473502/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/royal-challengers-bengaluru-vs-sunrisers-hyderabad-65th-match-1473503/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/delhi-capitals-vs-punjab-kings-66th-match-1485779/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/gujarat-titans-vs-chennai-super-kings-67th-match-1473504/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/kolkata-knight-riders-vs-sunrisers-hyderabad-68th-match-1473505/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/mumbai-indians-vs-punjab-kings-69th-match-1473506/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/lucknow-super-giants-vs-royal-challengers-bengaluru-70th-match-1473507/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/punjab-kings-vs-royal-challengers-bengaluru-qualifier-1-1473508/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/gujarat-titans-vs-mumbai-indians-eliminator-1473509/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/mumbai-indians-vs-punjab-kings-qualifier-2-1473510/',
     'https://www.espncricinfo.com/series/ipl-2025-1449924/punjab-kings-vs-royal-challengers-bengaluru-final-1473511/']

In [4]:
len(urls)

71

In [5]:
#Header
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "Accept-Language": "en-US,en;q=0.9",
    "Referer": "https://www`.google.com/"}

In [6]:
for i in urls:
    url=i+'live-cricket-score'
    #Getting data by sending the request
    response=requests.get(url,headers=headers)
    if response.status_code==200:
        soup=BeautifulSoup(response.text,'html.parser')
        
        #Extracing the Venue and City details
        
        vd=soup.find('span',class_='ds-text-link-3 ds-font-medium ds-block ds-text-color-text ds-underline ds-decoration-color-text-tertiary hover:ds-text-color-primary hover:ds-decoration-color-primary')
        d=vd.text
        venue.append(d.split(',')[0])
        city.append(d.split(',')[1].strip())
       
        #Toss  details

        abbr_map = {
            "Sunrisers Hyderabad": "SRH",
            "Punjab Kings": "PBKS"
        }
        
        def team_abbr(team):
            team = team.strip()
        
            if team in abbr_map:
                return abbr_map[team]
        
            return "".join(word[0] for word in team.split())
            
        toss_details=soup.find('span',class_='ds-text-link-3 ds-font-medium ds-text-color-text ds-decoration-color-text-tertiary')
        tde=toss_details.text
        
        tow.append(tde.split(',')[0])
        tod.append("field" if "field" in tde.lower() else "bat")

        #Extrcating toss winner name as Short form Eg: Gujarat Giants as GT
        

        # Extracting the Match date
        
        for m in soup.find_all('span',class_='ds-text-link-3 ds-font-medium ds-text-color-text'):
            n=m.text
            if 'over' in n:
                match_date.append(' '.join(n.split()[0:3]))

In [7]:
len(venue),len(city),len(match_date),len(tow),len(tod)

(71, 71, 71, 71, 71)

In [8]:
tod

['field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'bat',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'bat',
 'field',
 'field',
 'field',
 'field',
 'bat',
 'field',
 'field',
 'field',
 'field',
 'bat',
 'field',
 'field',
 'field',
 'bat',
 'field',
 'field',
 'field',
 'field',
 'bat',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'bat',
 'field',
 'field',
 'bat',
 'bat',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'field',
 'bat',
 'bat',
 'field',
 'field',
 'field',
 'bat',
 'field',
 'field']

In [9]:
tow = [team_abbr(team) for team in tow]
tow

['RCB',
 'RR',
 'CSK',
 'DC',
 'GT',
 'KKR',
 'LSG',
 'CSK',
 'MI',
 'SRH',
 'CSK',
 'MI',
 'PBKS',
 'GT',
 'SRH',
 'MI',
 'DC',
 'PBKS',
 'GT',
 'MI',
 'KKR',
 'PBKS',
 'RR',
 'DC',
 'KKR',
 'LSG',
 'PBKS',
 'RCB',
 'DC',
 'CSK',
 'PBKS',
 'RR',
 'MI',
 'PBKS',
 'GT',
 'LSG',
 'RCB',
 'MI',
 'KKR',
 'DC',
 'MI',
 'RR',
 'SRH',
 'LSG',
 'RCB',
 'RR',
 'DC',
 'PBKS',
 'RR',
 'SRH',
 'CSK',
 'KKR',
 'LSG',
 'GT',
 'KKR',
 'PBKS',
 'GT',
 'SRH',
 'RR',
 'DC',
 'GT',
 'RCB',
 'DC',
 'CSK',
 'SRH',
 'PBKS',
 'RCB',
 'RCB',
 'MI',
 'PBKS',
 'PBKS']

In [10]:
#First innings data paths
innings1_paths=['Ball by Ball Commentary & Live Score - KKR vs RCB, 1st Match.html',
     'Ball by Ball Commentary & Live Score - SRH vs RR, 2nd Match.html',
     'Ball by Ball Commentary & Live Score - CSK vs MI, 3rd Match.html',
     'Ball by Ball Commentary & Live Score - DC vs LSG, 4th Match.html',
     'Ball by Ball Commentary & Live Score - GT vs PBKS, 5th Match.html',
     'Ball by Ball Commentary & Live Score - RR vs KKR, 6th Match.html',
     'Ball by Ball Commentary & Live Score - SRH vs LSG, 7th Match.html',
     'Ball by Ball Commentary & Live Score - CSK vs RCB, 8th Match.html',
     'Ball by Ball Commentary & Live Score - GT vs MI, 9th Match.html',
     'Ball by Ball Commentary & Live Score - DC vs SRH, 10th Match.html',
     'Ball by Ball Commentary & Live Score - RR vs CSK, 11th Match.html',
     'Ball by Ball Commentary & Live Score - MI vs KKR, 12th Match.html',
     'Ball by Ball Commentary & Live Score - LSG vs PBKS, 13th Match.html',
     'Ball by Ball Commentary & Live Score - RCB vs GT, 14th Match.html',
     'Ball by Ball Commentary & Live Score - KKR vs SRH, 15th Match.html',
     'Ball by Ball Commentary & Live Score - LSG vs MI, 16th Match.html',
     'Ball by Ball Commentary & Live Score - CSK vs DC, 17th Match.html',
     'Ball by Ball Commentary & Live Score - PBKS vs RR, 18th Match.html',
     'Ball by Ball Commentary & Live Score - SRH vs GT, 19th Match.html',
     'Ball by Ball Commentary & Live Score - MI vs RCB, 20th Match.html',
     'Ball by Ball Commentary & Live Score - KKR vs LSG, 21st Match.html',
     'Ball by Ball Commentary & Live Score - PBKS vs CSK, 22nd Match.html',
     'Ball by Ball Commentary & Live Score - GT vs RR, 23rd Match.html',
     'Ball by Ball Commentary & Live Score - RCB vs DC, 24th Match.html',
     'Ball by Ball Commentary & Live Score - CSK vs KKR, 25th Match.html',
     'Ball by Ball Commentary & Live Score - LSG vs GT, 26th Match.html',
     'Ball by Ball Commentary & Live Score - SRH vs PBKS, 27th Match.html',
     'Ball by Ball Commentary & Live Score - RR vs RCB, 28th Match.html',
     'Ball by Ball Commentary & Live Score - DC vs MI, 29th Match.html',
     'Ball by Ball Commentary & Live Score - LSG vs CSK, 30th Match.html',
     'Ball by Ball Commentary & Live Score - PBKS vs KKR, 31st Match.html',
     'Ball by Ball Commentary & Live Score - DC vs RR, 32nd Match.html',
     'Ball by Ball Commentary & Live Score - MI vs SRH, 33rd Match.html',
     'Ball by Ball Commentary & Live Score - RCB vs PBKS, 34th Match.html',
     'Ball by Ball Commentary & Live Score - GT vs DC, 35th Match.html',
     'Ball by Ball Commentary & Live Score - RR vs LSG, 36th Match.html',
     'Ball by Ball Commentary & Live Score - PBKS vs RCB, 37th Match.html',
     'Ball by Ball Commentary & Live Score - MI vs CSK, 38th Match.html',
     'Ball by Ball Commentary & Live Score - KKR vs GT, 39th Match 1.html',
     'Ball by Ball Commentary & Live Score - LSG vs DC, 40th Match.html',
     'Ball by Ball Commentary & Live Score - SRH vs MI, 41st Match.html',
     'Ball by Ball Commentary & Live Score - RCB vs RR, 42nd Match.html',
     'Ball by Ball Commentary & Live Score - CSK vs SRH, 43rd Match.html',
     'Ball by Ball Commentary & Live Score - MI vs LSG, 45th Match.html',
     'Ball by Ball Commentary & Live Score - DC vs RCB, 46th Match.html',
     'Ball by Ball Commentary & Live Score - RR vs GT, 47th Match.html',
     'Ball by Ball Commentary & Live Score - DC vs KKR, 48th Match.html',
     'Ball by Ball Commentary & Live Score - CSK vs PBKS, 49th Match.html',
     'Ball by Ball Commentary & Live Score - RR vs MI, 50th Match.html',
     'Ball by Ball Commentary & Live Score - GT vs SRH, 51st Match.html',
     'Ball by Ball Commentary & Live Score - RCB vs CSK, 52nd Match.html',
     'Ball by Ball Commentary & Live Score - KKR vs RR, 53rd Match.html',
     'Ball by Ball Commentary & Live Score - PBKS vs LSG, 54th Match.html',
     'Ball by Ball Commentary & Live Score - MI vs GT, 56th Match.html',
     'Ball by Ball Commentary & Live Score - KKR vs CSK, 57th Match.html',
     'Ball by Ball Commentary & Live Score - RR vs PBKS, 59th Match.html',
     'Ball by Ball Commentary & Live Score - DC vs GT, 60th Match.html',
     'Ball by Ball Commentary & Live Score - LSG vs SRH, 61st Match.html',
     'Ball by Ball Commentary & Live Score - CSK vs RR, 62nd Match.html',
     'Ball by Ball Commentary & Live Score - MI vs DC, 63rd Match.html',
     'Ball by Ball Commentary & Live Score - GT vs LSG, 64th Match.html',
     'Ball by Ball Commentary & Live Score - RCB vs SRH, 65th Match.html',
     'Ball by Ball Commentary & Live Score - DC vs PBKS, 66th Match.html',
     'Ball by Ball Commentary & Live Score - GT vs CSK, 67th Match.html',
     'Ball by Ball Commentary & Live Score - KKR vs SRH, 68th Match.html',
     'Ball by Ball Commentary & Live Score - MI vs PBKS, 69th Match.html',
     'Ball by Ball Commentary & Live Score - LSG vs RCB, 70th Match.html',
     'Ball by Ball Commentary & Live Score - PBKS vs RCB, Qualifier 1.html',
     'Ball by Ball Commentary & Live Score - GT vs MI, Eliminator.html',
     'Ball by Ball Commentary & Live Score - MI vs PBKS, Qualifier 2.html',
     'Ball by Ball Commentary & Live Score - PBKS vs RCB, Final.html'
    ]

In [11]:
#Second innings data paths
innings2_paths=['Ball by Ball Commentary & Live Score - KKR vs RCB, 1st Match1.html',
     'Ball by Ball Commentary & Live Score - SRH vs RR, 2nd Match1.html',
     'Ball by Ball Commentary & Live Score - CSK vs MI, 3rd Match1.html',
     'Ball by Ball Commentary & Live Score - DC vs LSG, 4th Match1.html',
     'Ball by Ball Commentary & Live Score - GT vs PBKS, 5th Match1.html',
     'Ball by Ball Commentary & Live Score - RR vs KKR, 6th Match1.html',
     'Ball by Ball Commentary & Live Score - SRH vs LSG, 7th Match1.html',
     'Ball by Ball Commentary & Live Score - CSK vs RCB, 8th Match1.html',
     'Ball by Ball Commentary & Live Score - GT vs MI, 9th Match1.html',
     'Ball by Ball Commentary & Live Score - DC vs SRH, 10th Match1.html',
     'Ball by Ball Commentary & Live Score - RR vs CSK, 11th Match1.html',
     'Ball by Ball Commentary & Live Score - MI vs KKR, 12th Match1.html',
     'Ball by Ball Commentary & Live Score - LSG vs PBKS, 13th Match1.html',
     'Ball by Ball Commentary & Live Score - RCB vs GT, 14th Match1.html',
     'Ball by Ball Commentary & Live Score - KKR vs SRH, 15th Match1.html',
     'Ball by Ball Commentary & Live Score - LSG vs MI, 16th Match1.html',
     'Ball by Ball Commentary & Live Score - CSK vs DC, 17th Match1.html',
     'Ball by Ball Commentary & Live Score - PBKS vs RR, 18th Match1.html',
     'Ball by Ball Commentary & Live Score - SRH vs GT, 19th Match1.html',
     'Ball by Ball Commentary & Live Score - MI vs RCB, 20th Match1.html',
     'Ball by Ball Commentary & Live Score - KKR vs LSG, 21st Match1.html',
     'Ball by Ball Commentary & Live Score - PBKS vs CSK, 22nd Match1.html',
     'Ball by Ball Commentary & Live Score - GT vs RR, 23rd Match1.html',
     'Ball by Ball Commentary & Live Score - RCB vs DC, 24th Match1.html',
     'Ball by Ball Commentary & Live Score - CSK vs KKR, 25th Match1.html',
     'Ball by Ball Commentary & Live Score - LSG vs GT, 26th Match 1.html',
     'Ball by Ball Commentary & Live Score - SRH vs PBKS, 27th Match 1.html',
     'Ball by Ball Commentary & Live Score - RR vs RCB, 28th Match 1.html',
     'Ball by Ball Commentary & Live Score - DC vs MI, 29th Match 1.html',
     'Ball by Ball Commentary & Live Score - LSG vs CSK, 30th Match 1.html',
     'Ball by Ball Commentary & Live Score - PBKS vs KKR, 31st Match 1.html',
     'Ball by Ball Commentary & Live Score - DC vs RR, 32nd Match 1.html',
     'Ball by Ball Commentary & Live Score - MI vs SRH, 33rd Match 1.html',
     'Ball by Ball Commentary & Live Score - RCB vs PBKS, 34th Match 1.html',
     'Ball by Ball Commentary & Live Score - GT vs DC, 35th Match 1.html',
     'Ball by Ball Commentary & Live Score - RR vs LSG, 36th Match 1.html',
     'Ball by Ball Commentary & Live Score - PBKS vs RCB, 37th Match 1.html',
     'Ball by Ball Commentary & Live Score - MI vs CSK, 38th Match 1.html',
     'Ball by Ball Commentary & Live Score - KKR vs GT, 39th Match.html',
     'Ball by Ball Commentary & Live Score - LSG vs DC, 40th Match 1.html',
     'Ball by Ball Commentary & Live Score - SRH vs MI, 41st Match1.html',
     'Ball by Ball Commentary & Live Score - RCB vs RR, 42nd Match 1.html',
     'Ball by Ball Commentary & Live Score - CSK vs SRH, 43rd Match 1.html',
     'Ball by Ball Commentary & Live Score - MI vs LSG, 45th Match 1.html',
     'Ball by Ball Commentary & Live Score - DC vs RCB, 46th Match 1.html',
     'Ball by Ball Commentary & Live Score - RR vs GT, 47th Match 1.html',
     'Ball by Ball Commentary & Live Score - DC vs KKR, 48th Match 1.html',
     'Ball by Ball Commentary & Live Score - CSK vs PBKS, 49th Match 1.html',
     'Ball by Ball Commentary & Live Score - RR vs MI, 50th Match 1.html',
     'Ball by Ball Commentary & Live Score - GT vs SRH, 51st Match 1.html',
     'Ball by Ball Commentary & Live Score - RCB vs CSK, 52nd Match 1.html',
     'Ball by Ball Commentary & Live Score - KKR vs RR, 53rd Match 1.html',
     'Ball by Ball Commentary & Live Score - PBKS vs LSG, 54th Match 1.html',
     'Ball by Ball Commentary & Live Score - MI vs GT, 56th Match 1.html',
     'Ball by Ball Commentary & Live Score - KKR vs CSK, 57th Match 1.html',
     'Ball by Ball Commentary & Live Score - RR vs PBKS, 59th Match 1.html',
     'Ball by Ball Commentary & Live Score - DC vs GT, 60th Match 1.html',
     'Ball by Ball Commentary & Live Score - LSG vs SRH, 61st Match 1.html',
     'Ball by Ball Commentary & Live Score - CSK vs RR, 62nd Match 1.html',
     'Ball by Ball Commentary & Live Score - MI vs DC, 63rd Match 1.html',
     'Ball by Ball Commentary & Live Score - GT vs LSG, 64th Match1.html',
     'Ball by Ball Commentary & Live Score - RCB vs SRH, 65th Match 1.html',
     'Ball by Ball Commentary & Live Score - DC vs PBKS, 66th Match 1.html',
     'Ball by Ball Commentary & Live Score - GT vs CSK, 67th Match 1.html',
     'Ball by Ball Commentary & Live Score - KKR vs SRH, 68th Match 1.html',
     'Ball by Ball Commentary & Live Score - MI vs PBKS, 69th Match 1.html',
     'Ball by Ball Commentary & Live Score - LSG vs RCB, 70th Match 1.html',
     'Ball by Ball Commentary & Live Score - PBKS vs RCB, Qualifier 11.html',
     'Ball by Ball Commentary & Live Score - GT vs MI, Eliminator 1.html',
     'Ball by Ball Commentary & Live Score - MI vs PBKS, Qualifier 2 1.html',
     'Ball by Ball Commentary & Live Score - PBKS vs RCB, Final 1.html'
    ]

In [12]:
len(innings1_paths),len(innings2_paths)

(71, 71)

In [13]:
# This need to be add in the innings paths
for path in innings1_paths:
    match_num.append(path.split(',')[1].split('.')[0].strip())

In [14]:
len(match_num)

71

In [15]:
# This need to be add in the innings paths
for path in innings1_paths:
    team1_list.append(path.split(',')[0][39:].split('vs')[0].strip())
for path in innings2_paths:
    team2_list.append(path.split(',')[0][39:].split('vs')[1].strip())

In [16]:
team1_list

['KKR',
 'SRH',
 'CSK',
 'DC',
 'GT',
 'RR',
 'SRH',
 'CSK',
 'GT',
 'DC',
 'RR',
 'MI',
 'LSG',
 'RCB',
 'KKR',
 'LSG',
 'CSK',
 'PBKS',
 'SRH',
 'MI',
 'KKR',
 'PBKS',
 'GT',
 'RCB',
 'CSK',
 'LSG',
 'SRH',
 'RR',
 'DC',
 'LSG',
 'PBKS',
 'DC',
 'MI',
 'RCB',
 'GT',
 'RR',
 'PBKS',
 'MI',
 'KKR',
 'LSG',
 'SRH',
 'RCB',
 'CSK',
 'MI',
 'DC',
 'RR',
 'DC',
 'CSK',
 'RR',
 'GT',
 'RCB',
 'KKR',
 'PBKS',
 'MI',
 'KKR',
 'RR',
 'DC',
 'LSG',
 'CSK',
 'MI',
 'GT',
 'RCB',
 'DC',
 'GT',
 'KKR',
 'MI',
 'LSG',
 'PBKS',
 'GT',
 'MI',
 'PBKS']

In [17]:
team2_list

['RCB',
 'RR',
 'MI',
 'LSG',
 'PBKS',
 'KKR',
 'LSG',
 'RCB',
 'MI',
 'SRH',
 'CSK',
 'KKR',
 'PBKS',
 'GT',
 'SRH',
 'MI',
 'DC',
 'RR',
 'GT',
 'RCB',
 'LSG',
 'CSK',
 'RR',
 'DC',
 'KKR',
 'GT',
 'PBKS',
 'RCB',
 'MI',
 'CSK',
 'KKR',
 'RR',
 'SRH',
 'PBKS',
 'DC',
 'LSG',
 'RCB',
 'CSK',
 'GT',
 'DC',
 'MI',
 'RR',
 'SRH',
 'LSG',
 'RCB',
 'GT',
 'KKR',
 'PBKS',
 'MI',
 'SRH',
 'CSK',
 'RR',
 'LSG',
 'GT',
 'CSK',
 'PBKS',
 'GT',
 'SRH',
 'RR',
 'DC',
 'LSG',
 'SRH',
 'PBKS',
 'CSK',
 'SRH',
 'PBKS',
 'RCB',
 'RCB',
 'MI',
 'PBKS',
 'RCB']

In [18]:
from bs4 import BeautifulSoup
import pandas as pd

VENUE = []
CITY = []
MATCH_DATE = []
MATCH_NUMBER = []
TOSS_WINNER = []
TOSS_DECISION = []

for path1, path2, team1, team2, toswi, tosde, ven, cit, mdate, mnum in zip(
        innings1_paths,
        innings2_paths,
        team1_list,
        team2_list,
        tow,
        tod,
        venue,
        city,
        match_date,
        match_num
        ):

    # ============ FIRST INNINGS ============

    with open(path1, encoding="utf-8") as fp:
        soup = BeautifulSoup(fp, 'html.parser')

    s_o = []
    for div in soup.find_all('div', class_='lg:ds-flex lg:ds-items-center lg:ds-px-2'):
        for i in div.find_all('span'):
            s_o.append(i.text)

    com = []
    for div in soup.find_all('div', class_='ds-leading-[16px] lg:ds-leading-none ds-mb-0.5'):
        for i in div.find_all('span'):
            com.append(i.text)

    text_blocks = [i.split(',')[0] for i in com[::2]]

    # determine teams for 1st innings
    if tosde.lower() == "field":
        if toswi == team1:
            bat1, bowl1 = team2, team1
        else:
            bat1, bowl1 = team1, team2
    else:
        bat1 = toswi
        bowl1 = team2 if toswi == team1 else team1

    '''for ov, sc, txt in zip(s_o[::2], s_o[1::2], text_blocks):

        over.append(int(ov.split('.')[0]) + 1)
        ball.append(ov.split('.')[-1])
        score.append('0' if sc == 'â€¢' else sc)

        batter.append(txt.split('to')[-1].strip())
        bowling.append(txt.split('to')[0].strip())

        batting_team.append(bat1)
        bowling_team.append(bowl1)
        innings.append(1)

        VENUE.append(ven)
        CITY.append(cit)
        MATCH_DATE.append(mdate)
        TOSS_WINNER.append(toswi)
        TOSS_DECISION.append(tosde)
        MATCH_NUMBER.append(mnum)'''
    for ov, sc, txt in zip(s_o[::2], s_o[1::2], text_blocks):

        over.append(int(ov.split('.')[0]) + 1)
        ball.append(ov.split('.')[-1])
        score.append('0' if sc == 'â€¢' else sc)
    
        batter.append(txt.split('to')[-1].strip())
        bowling.append(txt.split('to')[0].strip())
    
        batting_team.append(bat1)
        bowling_team.append(bowl1)
        innings.append(1)
    
        # 🔒 ALWAYS append metadata here
        MATCH_NUMBER.append(mnum)
        MATCH_DATE.append(mdate)
        VENUE.append(ven)
        CITY.append(cit)
        TOSS_WINNER.append(toswi)
        TOSS_DECISION.append(tosde)

        

    # ============ SECOND INNINGS ============

    with open(path2, encoding="utf-8") as fp:
        soup = BeautifulSoup(fp, 'html.parser')

    s_o = []
    for div in soup.find_all('div', class_='lg:ds-flex lg:ds-items-center lg:ds-px-2'):
        for i in div.find_all('span'):
            s_o.append(i.text)

    com = []
    for div in soup.find_all('div', class_='ds-leading-[16px] lg:ds-leading-none ds-mb-0.5'):
        for i in div.find_all('span'):
            com.append(i.text)

    text_blocks = [i.split(',')[0] for i in com[::2]]

    bat2, bowl2 = bowl1, bat1   # swap teams

    '''for ov, sc, txt in zip(s_o[::2], s_o[1::2], text_blocks):

        over.append(int(ov.split('.')[0]) + 1)
        ball.append(ov.split('.')[-1])
        score.append('0' if sc == 'â€¢' else sc)

        batter.append(txt.split()[-1])
        bowling.append(txt.split('to')[0].strip())

        batting_team.append(bat2)
        bowling_team.append(bowl2)
        innings.append(2)

        VENUE.append(ven)
        CITY.append(cit)
        MATCH_DATE.append(mdate)
        TOSS_WINNER.append(toswi)
        TOSS_DECISION.append(tosde)
        MATCH_NUMBER.append(mnum)'''
    
    for ov, sc, txt in zip(s_o[::2], s_o[1::2], text_blocks):

        over.append(int(ov.split('.')[0]) + 1)
        ball.append(ov.split('.')[-1])
        score.append('0' if sc == 'â€¢' else sc)
    
        batter.append(txt.split('to')[-1].strip())
        bowling.append(txt.split('to')[0].strip())
    
        batting_team.append(bat2)
        bowling_team.append(bowl2)
        innings.append(2)
    
        # 🔒 ALWAYS append metadata here
        MATCH_NUMBER.append(mnum)
        MATCH_DATE.append(mdate)
        VENUE.append(ven)
        CITY.append(cit)
        TOSS_WINNER.append(toswi)
        TOSS_DECISION.append(tosde)

    print(path1)

    


# ============ FINAL DATAFRAME ============

Ball by Ball Commentary & Live Score - KKR vs RCB, 1st Match.html
Ball by Ball Commentary & Live Score - SRH vs RR, 2nd Match.html
Ball by Ball Commentary & Live Score - CSK vs MI, 3rd Match.html
Ball by Ball Commentary & Live Score - DC vs LSG, 4th Match.html
Ball by Ball Commentary & Live Score - GT vs PBKS, 5th Match.html
Ball by Ball Commentary & Live Score - RR vs KKR, 6th Match.html
Ball by Ball Commentary & Live Score - SRH vs LSG, 7th Match.html
Ball by Ball Commentary & Live Score - CSK vs RCB, 8th Match.html
Ball by Ball Commentary & Live Score - GT vs MI, 9th Match.html
Ball by Ball Commentary & Live Score - DC vs SRH, 10th Match.html
Ball by Ball Commentary & Live Score - RR vs CSK, 11th Match.html
Ball by Ball Commentary & Live Score - MI vs KKR, 12th Match.html
Ball by Ball Commentary & Live Score - LSG vs PBKS, 13th Match.html
Ball by Ball Commentary & Live Score - RCB vs GT, 14th Match.html
Ball by Ball Commentary & Live Score - KKR vs SRH, 15th Match.html
Ball by Ball Commentary & Live Score - LSG vs MI, 16th Match.html
Ball by Ball Commentary & Live Score - CSK vs DC, 17th Match.html
Ball by Ball Commentary & Live Score - PBKS vs RR, 18th Match.html
Ball by Ball Commentary & Live Score - SRH vs GT, 19th Match.html
Ball by Ball Commentary & Live Score - MI vs RCB, 20th Match.html
Ball by Ball Commentary & Live Score - KKR vs LSG, 21st Match.html
Ball by Ball Commentary & Live Score - PBKS vs CSK, 22nd Match.html
Ball by Ball Commentary & Live Score - GT vs RR, 23rd Match.html
Ball by Ball Commentary & Live Score - RCB vs DC, 24th Match.html
Ball by Ball Commentary & Live Score - CSK vs KKR, 25th Match.html
Ball by Ball Commentary & Live Score - LSG vs GT, 26th Match.html
Ball by Ball Commentary & Live Score - SRH vs PBKS, 27th Match.html
Ball by Ball Commentary & Live Score - RR vs RCB, 28th Match.html
Ball by Ball Commentary & Live Score - DC vs MI, 29th Match.html
Ball by Ball Commentary & Live Score - LSG vs CSK, 30th Match.html
Ball by Ball Commentary & Live Score - PBKS vs KKR, 31st Match.html
Ball by Ball Commentary & Live Score - DC vs RR, 32nd Match.html
Ball by Ball Commentary & Live Score - MI vs SRH, 33rd Match.html
Ball by Ball Commentary & Live Score - RCB vs PBKS, 34th Match.html
Ball by Ball Commentary & Live Score - GT vs DC, 35th Match.html
Ball by Ball Commentary & Live Score - RR vs LSG, 36th Match.html
Ball by Ball Commentary & Live Score - PBKS vs RCB, 37th Match.html
Ball by Ball Commentary & Live Score - MI vs CSK, 38th Match.html
Ball by Ball Commentary & Live Score - KKR vs GT, 39th Match 1.html
Ball by Ball Commentary & Live Score - LSG vs DC, 40th Match.html
Ball by Ball Commentary & Live Score - SRH vs MI, 41st Match.html
Ball by Ball Commentary & Live Score - RCB vs RR, 42nd Match.html
Ball by Ball Commentary & Live Score - CSK vs SRH, 43rd Match.html
Ball by Ball Commentary & Live Score - MI vs LSG, 45th Match.html
Ball by Ball Commentary & Live Score - DC vs RCB, 46th Match.html
Ball by Ball Commentary & Live Score - RR vs GT, 47th Match.html
Ball by Ball Commentary & Live Score - DC vs KKR, 48th Match.html
Ball by Ball Commentary & Live Score - CSK vs PBKS, 49th Match.html
Ball by Ball Commentary & Live Score - RR vs MI, 50th Match.html
Ball by Ball Commentary & Live Score - GT vs SRH, 51st Match.html
Ball by Ball Commentary & Live Score - RCB vs CSK, 52nd Match.html
Ball by Ball Commentary & Live Score - KKR vs RR, 53rd Match.html
Ball by Ball Commentary & Live Score - PBKS vs LSG, 54th Match.html
Ball by Ball Commentary & Live Score - MI vs GT, 56th Match.html
Ball by Ball Commentary & Live Score - KKR vs CSK, 57th Match.html
Ball by Ball Commentary & Live Score - RR vs PBKS, 59th Match.html
Ball by Ball Commentary & Live Score - DC vs GT, 60th Match.html
Ball by Ball Commentary & Live Score - LSG vs SRH, 61st Match.html
Ball by Ball Commentary & Live Score - CSK vs RR, 62nd Match.html
Ball by Ball Commentary & Live Score - MI vs DC, 63rd Match.html
Ball by Ball Commentary & Live Score - GT vs LSG, 64th Match.html
Ball by Ball Commentary & Live Score - RCB vs SRH, 65th Match.html
Ball by Ball Commentary & Live Score - DC vs PBKS, 66th Match.html
Ball by Ball Commentary & Live Score - GT vs CSK, 67th Match.html
Ball by Ball Commentary & Live Score - KKR vs SRH, 68th Match.html
Ball by Ball Commentary & Live Score - MI vs PBKS, 69th Match.html
Ball by Ball Commentary & Live Score - LSG vs RCB, 70th Match.html
Ball by Ball Commentary & Live Score - PBKS vs RCB, Qualifier 1.html
Ball by Ball Commentary & Live Score - GT vs MI, Eliminator.html
Ball by Ball Commentary & Live Score - MI vs PBKS, Qualifier 2.html
Ball by Ball Commentary & Live Score - PBKS vs RCB, Final.html

In [19]:
len(MATCH_NUMBER),len(MATCH_DATE),len(VENUE),len(CITY),len(TOSS_WINNER)

(16242, 16242, 16242, 16242, 16242)

In [20]:
len(TOSS_DECISION),len(innings),len(batting_team),len(bowling_team),len(batter),len(bowling),len(over),len(ball),len(score)

(16242, 16242, 16242, 16242, 16242, 16242, 16242, 16242, 16242)

In [21]:
df = pd.DataFrame({
    'Match Number':MATCH_NUMBER,
    'Match Date':MATCH_DATE,
    'Venue':VENUE,
    'City':CITY,
    'Toss Winner':TOSS_WINNER,
    'Toss Decision':TOSS_DECISION,
    "Innings": innings,
    'Batting Team':batting_team,
    'Bowling Team':bowling_team,
    "Batter": batter,
    "Bowler": bowling,
    "Over": over,
    "Ball": ball,
    "Score": score
})

df

,Match Number,Match Date,Venue,City,Toss Winner,Toss Decision,Innings,Batting Team,Bowling Team,Batter,Bowler,Over,Ball,Score
0,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,de Kock,Hazlewood,1,1,•
1,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,de Kock,Hazlewood,1,2,4
2,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,de Kock,Hazlewood,1,3,•
3,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,de Kock,Hazlewood,1,4,•
4,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,de Kock,Hazlewood,1,5,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16237,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Hazlewood,20,2,•
16238,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Hazlewood,20,3,6
16239,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Hazlewood,20,4,4
16240,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Hazlewood,20,5,6
16241,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Hazlewood,20,6,6

In [22]:
df.to_csv("IPL_2025_Ball_Analysis1.csv", index=False)

In [23]:
df.iloc[8855:9103,]

,Match Number,Match Date,Venue,City,Toss Winner,Toss Decision,Innings,Batting Team,Bowling Team,Batter,Bowler,Over,Ball,Score
8855,39th Match 1,21 April 2025,Eden Gardens,Kolkata,KKR,field,1,GT,KKR,B Sai Sudharsan,Arora,1,1,1w
8856,39th Match 1,21 April 2025,Eden Gardens,Kolkata,KKR,field,1,GT,KKR,B Sai Sudharsan,Arora,1,1,1
8857,39th Match 1,21 April 2025,Eden Gardens,Kolkata,KKR,field,1,GT,KKR,Gill,Arora,1,2,•
8858,39th Match 1,21 April 2025,Eden Gardens,Kolkata,KKR,field,1,GT,KKR,Gill,Arora,1,3,•
8859,39th Match 1,21 April 2025,Eden Gardens,Kolkata,KKR,field,1,GT,KKR,Gill,Arora,1,4,•
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9098,39th Match 1,21 April 2025,Eden Gardens,Kolkata,KKR,field,2,KKR,GT,Rinku Singh,Ishant Sharma,20,1,W
9099,39th Match 1,21 April 2025,Eden Gardens,Kolkata,KKR,field,2,KKR,GT,Harshit Rana,Ishant Sharma,20,2,•
9100,39th Match 1,21 April 2025,Eden Gardens,Kolkata,KKR,field,2,KKR,GT,Harshit Rana,Ishant Sharma,20,3,1
9101,39th Match 1,21 April 2025,Eden Gardens,Kolkata,KKR,field,2,KKR,GT,A Raghuvanshi,Ishant Sharma,20,4,6
9102,39th Match 1,21 April 2025,Eden Gardens,Kolkata,KKR,field,2,KKR,GT,A Raghuvanshi,Ishant Sharma,20,5,•

In [24]:
df['Match Number'].unique()

array(['1st Match', '2nd Match', '3rd Match', '4th Match', '5th Match',
       '6th Match', '7th Match', '8th Match', '9th Match', '10th Match',
       '11th Match', '12th Match', '13th Match', '14th Match',
       '15th Match', '16th Match', '17th Match', '18th Match',
       '19th Match', '20th Match', '21st Match', '22nd Match',
       '23rd Match', '24th Match', '25th Match', '26th Match',
       '27th Match', '28th Match', '29th Match', '30th Match',
       '31st Match', '32nd Match', '33rd Match', '34th Match',
       '35th Match', '36th Match', '37th Match', '38th Match',
       '39th Match 1', '40th Match', '41st Match', '42nd Match',
       '43rd Match', '45th Match', '46th Match', '47th Match',
       '48th Match', '49th Match', '50th Match', '51st Match',
       '52nd Match', '53rd Match', '54th Match', '56th Match',
       '57th Match', '59th Match', '60th Match', '61st Match',
       '62nd Match', '63rd Match', '65th Match', '66th Match',
       '67th Match', '68th Match', '69th Match', '70th Match',
       'Qualifier 1', 'Eliminator', 'Qualifier 2', 'Final'], dtype=object)

In [26]:
df.tail(18)

,Match Number,Match Date,Venue,City,Toss Winner,Toss Decision,Innings,Batting Team,Bowling Team,Batter,Bowler,Over,Ball,Score
16224,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Yash Dayal,18,1,1lb
16225,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Azmatullah,Yash Dayal,18,2,W
16226,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Jamieson,Yash Dayal,18,3,1lb
16227,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Yash Dayal,18,4,2
16228,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Yash Dayal,18,5,1
16229,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Jamieson,Yash Dayal,18,6,•
16230,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Bhuvneshwar,19,1,6
16231,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Bhuvneshwar,19,2,•
16232,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Bhuvneshwar,19,3,•
16233,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Bhuvneshwar,19,4,4
16234,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Bhuvneshwar,19,5,2
16235,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Bhuvneshwar,19,6,1
16236,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Hazlewood,20,1,•
16237,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Hazlewood,20,2,•
16238,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Hazlewood,20,3,6
16239,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Hazlewood,20,4,4
16240,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Hazlewood,20,5,6
16241,Final,3 June 2025,Narendra Modi Stadium,Ahmedabad,PBKS,field,2,PBKS,RCB,Shashank Singh,Hazlewood,20,6,6

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('IPL_2025_Analysis.csv')
df.head(10)

,Match Number,Match Date,Venue,City,Toss Winner,Toss Decision,Innings,Batting Team,Bowling Team,Batter,Bowler,Over,Ball,Score
0,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,de Kock,Hazlewood,1,1,•
1,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,de Kock,Hazlewood,1,2,4
2,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,de Kock,Hazlewood,1,3,•
3,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,de Kock,Hazlewood,1,4,•
4,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,de Kock,Hazlewood,1,5,W
5,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,Rahane,Hazlewood,1,6,•
6,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,Narine,Yash Dayal,2,1,•
7,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,Narine,Yash Dayal,2,2,•
8,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,Narine,Yash Dayal,2,3,•
9,1st Match,22 March 2025,Eden Gardens,Kolkata,RCB,field,1,KKR,RCB,Narine,Yash Dayal,2,4,•

In [5]:
df.loc[5190,'Score']='6'

In [6]:
df.to_csv("IPL2025_Ball_Analysis.csv", index=False)